//created on: Jan 28, 2015
package assets.axre.chores

//list any import classes here.
import com.concept.ruleengine.model.EphemeralMantle
import com.concept.ruleengine.common.util.AirportMath
import com.concept.ruleengine.common.util.CustomUtil
import com.concept.ruleengine.common.util.StringUtil
//declare any global variables here
global com.concept.ruleengine.reference.dao.ReferenceDAO reference
global com.concept.ruleengine.reference.mapper.QueryMapper mapper
global com.concept.ruleengine.dt.model.DecisionTable decisionTable


rule "initiation-calibration:input-assignation-s"
	salience 110
    when
        $em: EphemeralMantle(operationName == "trials-operation",
        	phase != null, 
    			round == 0
    			)
    then
    	$em.logs("the-sss");
    	
end


rule "initiation-calibration:input-assignation"
	salience 100
    when
        $em: EphemeralMantle(operationName == "trials-operation",
        	phase == "0000000", 
    			round == 0
    			)
    then
    	$em.facts.put("_1","lalala");
    	$em.setPhase("initiation-calibration:input-assignation");
    	$em.logs("initiation-calibration:input-assignation:trials-operation");
    	
end

rule "initiation-calibration:input-assignation-replicates"
	salience 70
    when
        $em: EphemeralMantle(operationName == "trials-operation",
        	phase == "0000000", 
        		!CustomUtil.isNull(facts.get("in1")),
    				round == 0
    			)
    then
    	$em.logs("this is called!!");
    	$em.facts.put("_1","lilili");
    	$em.setPhase("initiation--assignation");
    	update( $em );
end

rule "initiation-calibration:input-assignation-replicates-also"
	salience 50
    when
        $em: EphemeralMantle(operationName == "trials-operation",
        	phase == "0000000", 
        		facts.get("in1") == "100002880",
    				round == 0
    			)
    then
    	$em.logs("this is called also!!");
end

rule "initiation-calibration:input-assignation-replicates-also-called"
	salience 50
    when
        $em: EphemeralMantle(operationName == "trials-operation",
        	phase == "initiation-calibration:input-assignation", 
    			round == 0
    			)
    then
    	$em.logs("this is called also-dumbass!!, from "+$em.facts.get("_1"));
end


rule "initiation-calibration:reference#dt-retrieval-sample:valid"
    when
        $em: EphemeralMantle(operationName == "trials-operation",
        	phase == "initiation-calibration:input-assignation", 
    			round == 0, 
    				facts.get("mock-name") == "QueryMapper-xls"
    			)
    then
        $em.setPhase("initiation-calibration:reference#dt-retrieval-sample:valid");
        mapper.relace($em.facts.get("mock-key").toString(), $em.facts.get("mock-value").toString());
    	$em.facts.put("mock-result", reference.get(mapper.getQuery()));
        update( $em );
end

