//created on: Aug 29, 2015
package assets.axre.rule.apii.coop

//list any import classes here.
import com.concept.ruleengine.model.EphemeralMantle
import com.concept.ruleengine.common.util.StringUtil
import com.concept.ruleengine.common.util.DateUtil
import com.concept.ruleengine.common.util.CustomUtil

import com.concept.ruleengine.reference.dao.ReferenceDAO
import com.concept.ruleengine.reference.mapper.QueryMapper
import com.concept.ruleengine.dt.model.DecisionTable

import java.sql.Timestamp
import java.util.Date

global com.concept.ruleengine.reference.dao.ReferenceDAO reference
global com.concept.ruleengine.reference.mapper.QueryMapper mapper
global com.concept.ruleengine.dt.model.DecisionTable decisionTable

function EphemeralMantle initiation(EphemeralMantle em, DecisionTable decisionTable){
	em.facts.remap("in2", "_type");
	em.facts.put("maximumCapacity", 2);
	em.facts.put("timeBuffer", 15);
	
	
	decisionTable.relace("_xdt_op_nonservicetype");
	em.facts.putList("nonServicetypeList", StringUtil.toList(decisionTable.laced().get("LISTVALUE"), 
			StringUtil.CustomRegex.COMMA));

	return em;
}

function EphemeralMantle initiationBulkAllocation(EphemeralMantle em,
		QueryMapper mapper, ReferenceDAO reference){
		
	String eta = DateUtil.toString(
    		StringUtil.toTimestamp(em.facts.get("in0"), 
    			"yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"), "yyyy-MM-dd HH:mm:ss");
		
	em.facts.put("_inEtd", eta);
	
	mapper.relace("_sqlmap_co","count_bulk_rmsoperation");
	mapper.parameterized("ETAD",em.facts.get("_inEtd") );
	em.facts.put("bulksize", reference.getInt(mapper.getQuery()));
	
	em.facts.put("_rmsKey", 0);
	
	em.facts.put("bulkoffset", 0);
	em.facts.put("bulklimit", 10);
	
	return em;
}

rule "initiation-calibration:initiated-phase"
    when
        $em: EphemeralMantle(operationName == "carousel-operation",
        	phase == "0000000", 
        		round == 0
    			)
    then
    	$em = initiation($em, decisionTable);
    	$em.setPhase("initiation-calibration:input-validity");
    	update( $em );
end

/* Note from AION,
 * A: Bulk Processes/Manual 
 * B: Move button / drag and drop 
 * C: Conflicts 
 * D: From FMM 
 */
rule "bulk-allocation:determination"
    when
        $em: EphemeralMantle(operationName == "carousel-operation",
        	phase == "initiation-calibration:input-validity", 
        		round == 0, 
        			facts.get("_type") == "A",
        				!CustomUtil.isNullOrBlank(facts.get("in0"))
    			)
    then
    	$em.facts.put("capacity:i", 1);
		$em.facts.put("onfitnessAssignation", false);
		$em.facts.put("onCapacityCheck", false);
    
    	$em.setPhase("bulk-allocation");
    	$em.logs("START AS "+$em.getPhase());
    	$em = initiationBulkAllocation($em, mapper, reference);
    	update( $em );
end

rule "single-validation:determination"
    when
        $em: EphemeralMantle(operationName == "carousel-operation",
        	phase == "initiation-calibration:input-validity", 
        		round == 0, 
        			facts.get("_type") == "B",
        				!CustomUtil.isNullOrBlank(facts.get("in1")),
        				!CustomUtil.isNullOrBlank(facts.get("in3"))
    			)
    then
   		$em.facts.remap("in1", "_reclaimCode");
   		$em.facts.remap("in3", "_rmsKey");
   		
    	$em.setPhase("single-validation");
    	$em.logs("START AS "+$em.getPhase());
    	$em.facts.put("onfitnessAssignation", false);
    	update( $em );
    	
end

rule "single-allocation:determination"
    when
        $em: EphemeralMantle(operationName == "carousel-operation",
        	phase == "initiation-calibration:input-validity", 
        		round == 0, 
        			facts.get("_type") == "C",
        				!CustomUtil.isNullOrBlank(facts.get("in3"))
    			)
    then
    	$em.facts.remap("in3", "_rmsKey");
    	$em.facts.put("capacity:i", 1);
		$em.facts.put("onfitnessAssignation", false);
		$em.facts.put("onCapacityCheck", false);
    	
    	$em.setPhase("single-allocation");
    	$em.logs("START AS "+$em.getPhase());
    	update( $em );
end

rule "adhoc-allocation:determination"
    when
        $em: EphemeralMantle(operationName == "carousel-operation",
        	phase == "initiation-calibration:input-validity", 
        		round == 0, 
        			facts.get("_type") == "D",
        				!CustomUtil.isNullOrBlank(facts.get("in1")),
        				!CustomUtil.isNullOrBlank(facts.get("in3"))
    			)
    then
    	$em.facts.remap("in1", "_reclaimCode");
   		$em.facts.remap("in3", "_rmsKey");
   		
    	$em.setPhase("single-validation");
    	$em.logs("START AS "+$em.getPhase());
    	$em.facts.put("onfitnessAssignation", true);
    	update( $em );
end

